### PR TITLE
Lab3

### PR DESCRIPTION
**Pull request by cseydlitz**
@michaelGRU Please Review.

### CODE REVIEW

**Comment by michaelGRU** [comment]
nice work chelsea. I'm still having trouble reading your math equations in html preview
Q3, I think something is off about your graph. you asked "what is the probability that we received 6800 cosmic rays over this time?" this shouldn't be calculated using cdf, this is a pdf question, ie. what is the probability that we get a number that is exactly 6800 given the mean. The "new mean" for the background after 7200 convolution should just be the old mean times 7200, you should get 7200 rays/ 7200 min.

**Comment by cseydlitz** [comment]
Thanks for the suggestions @michaelGRU 
PDF added at the suggestion that math is unreadable; I suspect incompatibility with some HTML viewers and markdown.
I believe I have addressed all other concerns. Thank you for the input!
Note: Estimated Time to complete: 20 hours

**Comment by cseydlitz** [comment]
@oliviatessa please review

**Comment by oliviatessa** [comment]
Hi Chelsea, 

Here are my comments on your lab 3: 

P.1
- Really great discussion for this problem 
- Are there any other ways to remove bad data points close to the mean? (Think metadata)

P.2
- I understand where you are going with your statistical question, but I'm a little confused with what you mean by "standard deviation constraint." 
- Really good job with the rest of this problem. I think that the Rayleigh method is much easier to use and more widely applicable. 

P.3 
- Great job with this problem - only note is to explain in a little more detail how you used the CLT (if you used it.) 
- "which should be a Gaussian distribution because of the CLT, whose mean is 7200." I would go into a little more detail here. If the poisson really Gaussian after 15 iterations? Or does it just look Gaussian on a linear plot? 

Best, 
Olivia

**Pull request closed without merging**
