### PR TITLE
Lab2

### PR DESCRIPTION
**Pull request by cseydlitz**

### CODE REVIEW

**Comment by cseydlitz** [comment]
@anthonybotello please review. 

This is just a partial update. Only problem 1 is complete at this point.

For part 2 I'm planning on iterating over 100 or so iterations instead of just 4. 

I am still working on Part 4.

**Comment by anthonybotello** [comment]
I don't think we want to use mode='same' for the convolutions. For parts 1.A and 1.B, since we're summing over the days, and not averaging, the x-axis should be increasing since we're accumulating data. For part 1.C, the average background distribution should have more points as you average over more days, but the x-axis stays fixed by dividing it by the number of days you're averaging over.

Your solution to part 1.D really confuses me. It seems like you just computed the probability mass of a random point and called that your 'sigma'. I'm not even sure what you're using for your 
signal here. In any case, the goal is to sum your background over N days and calculate the probability that your signal of NxY gamma bursts could have been caused by your background summed over those N days. This probability is computed with the survival function of the distribution (**stats.poisson(mu).sf(NxY)**). Then (I'm not entirely sure about this part myself) the 'sigma' is calculated by feeding the probability to the inverse survival function of a standard gaussian distribution (**stats.norm.isf(probability)**).

For part 2, you may find it easier to use one of the distributions listed here:
https://en.wikipedia.org/wiki/List_of_convolutions_of_probability_distributions
This is, of course, just a suggestion. There is certainly nothing wrong with using the Rayleigh distribution.

We seem to be at about the same point in completing the lab, as you'll see in my pull request. This lab has been confusing for me as well. Let me know if you have anything you want to discuss.

**Comment by cseydlitz** [comment]
@oliviatessa Please review

Email sent in conjunction to explain the weird uploading.

**Comment by cseydlitz** [comment]
@oliviatessa 

I had to literally nuke all of jupyter from my computer to get it to work. 

I re-uploaded as it was, but now it's more cohesive. I changed NO code. However if you don't want to  use this and prefer to use what I submitted on Sunday then I understand. The option is there. 

sorry for all the terribleness

**Comment by cseydlitz** [comment]
Also for the record (since it's been announced that they want this), there's no way I spent less than 16 hours on this.

**Comment by oliviatessa** [comment]
Hi Chelsea, 

Here are my comments for your lab 2: 

P.1
- Can you show more concretely that the Poisson distributions are converging to Gaussian? (Try plotting a Gaussian and convolved Poisson side-by-side on a log scale)
- I don't understand what is going on in your part (D) plot. Can you rescale to make it more clear? 
- Try making your plots more self-contained by adding captions. Remember, you can repeat what is written in your discussion and just make it more concise. 

P.2 
- Again, you could see if these are truly starting to look Gaussian by using a log scale.
- I think this whole problem could use more discussion. Tell me _why_ it's becoming more Gaussian. 

P.3 
- It might be helpful (for you and the reader) to introduce the problem statements in your own words. This way each problem reads like a story - starting with a question. 
- In version 2, your plot isn't showing anything interesting. Maybe you need to adjust the axes? 

P.4 
- I don't think you fully understand the concepts explored in this problem. Trial factors are going to come up again in future labs, so make sure you understand these concepts going forward. 

Best, 
Olivia

**Pull request closed without merging**
