### PR TITLE
Final lab

### PR DESCRIPTION
**Pull request by cseydlitz**
@oliviatessa Please Review
Partial completion as there is an outstanding question.

### CODE REVIEW

**Comment by cseydlitz** [comment]
@oliviatessa @michaelGRU finished up 'lab 7'. 

I will continue adding on to this for 'lab 8'

**Comment by michaelGRU** [comment]
@cseydlitz we'll talk in person

**Comment by michaelGRU** [comment]
@cseydlitz much better. i think you're on the right track now. 
can you make two cuts? eg. make one on mass, and then make a second one on a different parameter that you found "discriminative", and see if it will increase the significance even further.

**Comment by michaelGRU** [comment]
make 2 "global" cuts. the cuts should change all parameters

**Comment by cseydlitz** [comment]
@michaelGRU 
@oliviatessa 

It's done
Feelin' a little like Frodo throwing the ring into Mt Doom.

**Comment by michaelGRU** [comment]
@cseydlitz Chelsea, it doesnt look like the plot is scaled properly. The real signal should look like a dot compared to the background. you want the sum of the signal events to equal to the expected yields. for instance, for every signal, you'd expect 2000 QCD background emerge at the same time, such that it is very challenging to find a Higgs signal. i can screenshot my plot and show it to you. my computer is really slow. I cant even convert my file into a pdf. Are you still alive?

**Pull request merged**
